package com.myspace.jboss_rule_engine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test1111 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	
	@org.kie.api.definition.type.Label(value = "aaaaa")
	private java.math.BigDecimal aaaaa;
	
	@org.kie.api.definition.type.Label(value = "bbbbbb")
	private java.lang.Boolean bbbbbb;

	public test1111() {
	}

	public java.math.BigDecimal getAaaaa() {
		return this.aaaaa;
	}

	public void setAaaaa(java.math.BigDecimal aaaaa) {
		this.aaaaa = aaaaa;
	}

	public java.lang.Boolean getBbbbbb() {
		return this.bbbbbb;
	}

	public void setBbbbbb(java.lang.Boolean bbbbbb) {
		this.bbbbbb = bbbbbb;
	}

	public test1111(java.math.BigDecimal aaaaa, java.lang.Boolean bbbbbb) {
		this.aaaaa = aaaaa;
		this.bbbbbb = bbbbbb;
	}

}